### ISSUE TITLE
trying to use your ipython plugin but get problem enabling it

### ISSUE THREAD

**Issue by dummys** [james91b/ida_ipython#1]
Hi,

When I type: ipython qtconsole --existing kernel-4221.json I get:

Traceback (most recent call last)
None
None:None

Did you have an idea ?
Latest version of IDA.

**Comment by james91b** [comment]
Hi, sorry i might not have made it clear you do need to run `ipython qtconsole --existing kernel-4221.json` at the windows command line. I'll update the readme. Please tell me if this solves your issue. Thanks!

**Comment by dummys** [comment]
yeah it's solved. Thanks a lot for this plugins!
