### ISSUE TITLE
IDAIPython crashes IDA if IDAPython is not loaded.

### ISSUE THREAD

**Issue by tmr232** [james91b/ida_ipython#22]
For some reason, installing Python 2.7.11 prevented IDAPython from working on my PC. As a result - IDAIPython kept crashing IDA, resulting in a dump file.

I am not yet sure why this happens, but we should probably check for IDAPython being loaded anyway.

**Comment by james91b** [comment]
I think we should call runplugin for the python plugin. It will ensure python is loaded first, and if it fails then we can just terminate ida_ipython.

**Comment by james91b** [comment]
Found the cause. It's the call to PyGILState_Ensure when python is not initialized. I will add in a check to ensure python is initialized.

**Comment by tmr232** [comment]
Sounds like a good solution to me.
