### ISSUE TITLE
Error: plugins\ida_ipython.plw cant load file

### ISSUE THREAD

**Issue by superr4y** [james91b/ida_ipython#23]
Hi have some trouble to install release 0.3/0.4.

Infos:
OS = Windows 7 64 VM
IDAPro 6.6 Portable
python 2.7.11 Anaconda 2.4.1 installed to C:\Anaconda2
set PYTHONHOME=C:\Anaconda2 global for all user 
copy python/ipythonEmbed.py to C:\Users\user\Desktop\IDAPro6.6\python\ipythonEmbed.py
copy plugins/ida_\* to  C:\Users\user\Desktop\IDAPro6.6\plugins\

execute  C:\Users\user\Desktop\IDAPro6.6\idaq.exe

ida pro console: 

```
LoadLibrary(C:\Users\user\Desktop\IDAPro6.6\plugins\ida_ipython.plw) error: Das angegebene Modul wurde nicht gefunden.
C:\Users\user\Desktop\IDAPro6.6\plugins\ida_ipython.plw: can't load file
```

Translate: Das angegebene Modul wurde nicht gefunden. => The module can not be found

Do I miss something? The file C:\Users\user\Desktop\IDAPro6.6\plugins\ida_ipython.plw exist and the user has rwx permissions.

**Comment by tmr232** [comment]
Can you check (using `procmon` or any other tool) which file is the one not found?

**Comment by superr4y** [comment]
Thanks for your fast response,
As far as I can see ida_ipython.plw can be opened but MSVCP140.dll can not be found.
So i installed https://www.microsoft.com/en-us/download/details.aspx?id=48145
Result: The Ida pro console message changed to

```
LoadLibrary(C:\Users\user\Desktop\IDAPro6.6\plugins\ida_ipython.plw) error: %1 ist keine zulässige Win32-Anwendung.
C:\Users\user\Desktop\IDAPro6.6\plugins\ida_ipython.plw: can't load file
```

Translage: error: %1 ist keine zulässige Win32-Anwendung. => error: 1% is not a valid win32 program

I also uploaded the pml file from procmon.
http://superr4y.net/idapro.pml.zip

EDIT: closed by accident... pushed the wrong button xD. Can not find a option to reopen.
EEDIT: I'm blind ^^

**Comment by tmr232** [comment]
Looking at the log, I didn't find any issues.

I can only suggest that you try and debug to see what fails to load.

**Comment by james91b** [comment]
Sounds like MSVC version issues. What version of MSVC is IDA using?

**Comment by superr4y** [comment]
IDA imports MSVCP100.dll
Hope I have some time next weekend to do more research.

**Comment by tmr232** [comment]
This is true up to 6.8. In 6.9 they switched compiler and went with `MSVCP140.dll`.
The thing is - it all seems to work just fine for me.

**Comment by superr4y** [comment]
I think it could be an issue with Anaconda. I have the same error when I try to load unicorn/capstone with anaconda python version while the default python version has not that issue. Have to test that in the next days, keep you updated ;-)

**Comment by james91b** [comment]
I've had issues before where compiling certain python dependencies on my own using disutils it generates an incompatible manifest and you end up in [MSVCRT.DLL hell](http://www.syndicateofideas.com/posts/fighting-the-msvcrt-dll-hell). It is one of the main reasons why i suggest getting the binary distribution using Anaconda.

Having said all that. If i remember correctly, IDAPython should just use Anaconda for the dependencies, not the actual python run time. The python run time is embedded within the IDAPython plugin. I think the cause for this issue might be a conflict between the python version embedded in IDAPython and the python library dependencies in anaconda. 

Try creating an Anaconda environment that uses the same Python version as the one embedded in IDAPython.

Here is how i made one for python 2.7.5. Try this in a command line session. This worked for me in IDA 6.6 
IDAPython v1.7.0 
ida_ipython 0.4

```
conda create --name py275 python=2.7.5 ipython notebook ipykernel
set PYTHONHOME=C:\Anaconda\envs\py275
"C:\Program Files (x86)\IDA 6.6\idaq.exe"
```

**Comment by superr4y** [comment]
Thank you for the help.

I tested this, but with no luck.

My embedded IDAPython version seems to be 2.7.2

```
Python 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)] 
IDAPython v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
```

When I try to create the environment with:

```
conda create --name py272 python=2.7.2 ipython notebook ipykernel
```

I get a "package python 2.7.2\* not found" error.

With python=2.7.5 the create command works but then IDAPython will not load when IDA is started.
Am I doing something obvious wrong here? I have no experience with Anaconda ^^

**Comment by james91b** [comment]
Looks like the python environment didn't change. Did you set you PYTHONHOME environment variable before launching IDA? Make sure all references on PATH environment variable now point to the new environment.

For example, you can do this in a command line session with.

```
set PYTHONHOME=C:\Anaconda\envs\py275
set PATH=%PYTHONHOME%;%PYTHONHOME%\Scripts;%PYTHONHOME%\Library\bin
set PYTHONPATH=
 "C:\Program Files (x86)\IDA 6.6\idaq.exe"
```

Make sure you launch IDA from that command line session. You could also update the variables in the system environment variables.

Also make sure that you are using this release of idapython. [idapython-1.7.0_ida6.6_py2.7_win32.zip](https://github.com/idapython/bin/blob/master/idapython-1.7.0_ida6.6_py2.7_win32.zip) and what is the error message that you are getting?

**Comment by superr4y** [comment]
First I execute:

```
conda create --name py275 python=2.7.5 ipython notebook ipykernel
```

to create the new environment. Then I start IDA with the following bat file:

```
set PYTHONHOME=C:\Anaconda2\envs\py275
set PATH=%PYTHONHOME%;%PYTHONHOME%\Scripts;%PYTHONHOME%\Library\bin
set PYTHONPATH=
idaq.exe
```

The bat file is in the IDA-Root directory. When executing the bat, IDA pops up a MessageBox: 'IDAPython: importing "site" failed' and IDA has no Python prompt but only IDC prompt. I can successfully import site from the python shell (PTHONHOME/PATH set to the py275 env).

When changing PYTHONHOME to C:\Anaconda2 or C:\Python27
IDA will start normaly but then IDA has the same error as described above while loading ida_ipython.plw. And the python version in IDA is 2.7.2. Am I right that this version should change to 2.7.5, or what do you mean by "Looks like the python environment didn't change"?

I also installed the idapython version you posted before. Installation was done as described in the README but I left out step 1 (Install 2.6 or 2.7 from http://www.python.org/).

Here some more infos just in case:

Python from the py275 environment:

```
Python 2.7.5 |Continuum Analytics, Inc.| (default, Jul  1 2013, 12:41:55) [MSC v
.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

Python from python.org:

```
Python 2.7.1 (r271:86832, Nov 27 2010, 18:30:46) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

Python from Anaconda2 folder:

```
Python 2.7.11 |Anaconda 2.4.1 (32-bit)| (default, Dec  7 2015, 14:13:17) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
```

**Comment by james91b** [comment]
If you remove ida_ipython plugin temporarily. Are you able to get IDA python plugin to load the Anaconda python environment?

**Comment by superr4y** [comment]
The same error occurs when ida_ipython is removed. I will try to find out why the site module can not be loaded, when Anaconda2 env is used.

**Comment by tmr232** [comment]
Somehow I missed that... You are using Python 2.7.11. There is a [known bug](https://bugs.python.org/issue25824) in Python 2.7.11 that makes it impossible to embed in other software.

Hex-Rays posted about it, including a work-around, in [their blog](http://www.hexblog.com/?p=949).

I believe that is the source of your issues.

**Comment by superr4y** [comment]
Sry for the long delay. I installed everything on a fresh windows and it works now.
Thank you all for you help :-)

**Comment by neatlife** [comment]
very helpful, thank you.
