### ISSUE TITLE
IDAPython crashes when IDASkins shows "First Start" dialog.

### ISSUE THREAD

**Issue by tmr232** [james91b/ida_ipython#29]
This is a clone of the issue I opened in IDASkins - https://github.com/zyantific/IDASkins/issues/9

I have IDAIPython installed for quite a long time, and it is working well.
Today I decided to try IDASkins. After installing it, IDA kept crashing on startup when starting to show the "First Start" dialog.
The crash seems to be related to the Python interpreter state, so I disabled my only non-default Python plugin - IDAIPython. Once done, everything worked as expected.
After the first run, I enabled IDAIPython, and all seems to work well.

I did not have time to dig in and see if this is a bug in IDAIPython or IDASkins, so I am opening an issue there as well, and referencing this one.

**Comment by james91b** [comment]
Hmm i was unable to re-produce this in my version of IDA. What version were you using?

**Comment by james91b** [comment]
Looking at the stack trace, probably an issue with the python plugin not having loaded yet. I think it will be fixed with the fix to #22 on release 0.5 branch now.

**Comment by athre0z** [comment]
It's worth pointing out that it only crashes when IDASkins opens the initial "Hey, wanna select a skin now?" modal (and thus blocks IDA from further startup). To see this dialog again after the very first start, you'll need to delete `HKEY_CURRENT_USER\SOFTWARE\athre0z\IDASkins`.

**Comment by tmr232** [comment]
@james91b makes sense. I forgot that the fix was not yet in the release. Any other features we want to add before another release?

**Comment by james91b** [comment]
@tmr232 I want to also get the clean shutdown into the next release. I have been having a look at the work you earlier.

**Comment by tmr232** [comment]
@james91b Ok. Sounds good. Maybe we should have milestones to assign relevant issues under?
