### ISSUE TITLE
Specify your license

### ISSUE THREAD

**Issue by obilodeau** [james91b/ida_ipython#5]
You don't mention under which terms you license your software. Unclear licensing will prevent people (like me) from contributing.

Github put up a nice website that helps with that decision and tells you what text to copy where: http://choosealicense.com/ 

More on the topic: http://www.datamation.com/open-source/open-source-debate-copyleft-vs.-permissive-licenses.html

**Comment by james91b** [comment]
Done, thank you for pointing it out.
