### ISSUE TITLE
Enable multiple notebook kernels

### ISSUE THREAD

**Issue by tmr232** [james91b/ida_ipython#7]
While IPython allowed to easily change profiles and kernels with `--profile` and other options, Jupyter does not.

The solution of using the `JUPYTER_CONFIG_DIR` environment variable works, but it is a very bad idea. Luckily, there is an alternative.

Jupyter allows for additional kernels to be added to the notebook using simple JSON files (docs [here](https://ipython.org/ipython-doc/dev/development/kernels.html#kernel-specs), examples [here](https://ocefpaf.github.io/python4oceanographers/blog/2014/09/01/ipython_kernel/)). The `kernel.json` files should be placed into a `kernels/<kernel-name>` directory under one of the data directories:

``` cmd
>>>jupyter --paths
config:
    C:\Users\user\.jupyter
    c:\python27\etc\jupyter
    C:\ProgramData\jupyter
data:
    C:\Users\user\AppData\Roaming\jupyter
    c:\python27\share\jupyter
    C:\ProgramData\jupyter
runtime:
    C:\Users\user\AppData\Roaming\jupyter\runtime
```

I tried using the following JSON:

``` json
{
 "display_name": "IDA64", 
 "language": "python", 
 "argv": [
  "python.exe", 
  "-c", "from idakernelmanager import main; main()",
  "-f", "{connection_file}"
 ], 
 "codemirror_mode": {
  "version": 2, 
  "name": "ipython"
 }
}
```

With the following code for `main`:

``` python
def main():
    kernel_cmd = [IDA_EXE] + sys.argv[-2:]
    return launch_ida_kernel(kernel_cmd)
```

It shows up nicely in the notebook,

![default](https://cloud.githubusercontent.com/assets/1386239/10250292/87836210-6932-11e5-909a-cb8813e7c340.PNG)

But trying to launch the `IDA64` kernel always yields the same error:

![default](https://cloud.githubusercontent.com/assets/1386239/10250189/07ef2cb4-6932-11e5-8cfa-b927e3a53d52.PNG)

Any ideas?

**Comment by james91b** [comment]
I think the best way is going to be just avoid the whole 'idakernelmanager' concept and use the Jupyter launching instead. 

After a fair bit of debugging. I manged to get it work using 

``` json
{
 "display_name": "IDA64", 
 "language": "python", 
 "argv": [
  "C:\\Program Files (x86)\\IDA 6.6\\idaq.exe", 
  "-Snothing.idc -f {connection_file}"  
 ], 
 "codemirror_mode": {
  "version": 2, 
  "name": "ipython"
 }
}
```

and fixing a bug in https://github.com/james91b/ida_ipython/blob/8f82f1ec7cf88ccc831533f1015cd0932344dd9b/python/ipythonEmbed.py#L58-L60 actidentally calling poller start twice. Which now breaks in Jupyter.

**Comment by tmr232** [comment]
Works for me too :+1: 

It's nice to get a better configuration for less code.

Will submit a PR tomorrow, along with fixing the import on [this line](https://github.com/james91b/ida_ipython/blob/8f82f1ec7cf88ccc831533f1015cd0932344dd9b/python/ipythonEmbed.py#L12) to match Jupyter as well.
